# PROFILE: debug
# /etc/sqm-autorate-debug.conf
upload_base_kbits=85000
download_base_kbits=830000

# Logging defaults
log_enabled=1
log_level=1

reflectors="1.1.1.1 208.67.222.222 208.67.220.220 9.9.9.9"

upload_min_percent=40
download_min_percent=40

increase_rate_percent_up=10
decrease_rate_percent_up=25
increase_rate_percent_down=10
decrease_rate_percent_down=20

delay_low_target_up=6
delay_high_target_up=8
delay_low_target_down=8
delay_high_target_down=10

latency_filter=median
latency_window_size=3

ping_interval_ms=150
ping_interval_fast_ms=100
elastic_probe=1
elastic_variance_ms=1

adaptive_floor=1
adaptive_floor_step=10
adaptive_floor_max=80
adaptive_floor_trigger_ms=10
adaptive_floor_trigger_count=2

# Decay settings
adaptive_floor_min=40
adaptive_floor_decay_interval=60
adaptive_floor_decay_step=10

load_aware=1
load_check_interval=2
load_bias_decrease=10
load_bias_threshold_bytes=2000000
