# PROFILE: gaming
# /etc/sqm-autorate-gaming.conf
upload_base_kbits=85000
download_base_kbits=830000

# Logging defaults
log_enabled=1
log_level=1

reflectors="1.1.1.1 208.67.222.222 208.67.220.220 9.9.9.9"

upload_min_percent=50
download_min_percent=55

increase_rate_percent_up=8
decrease_rate_percent_up=12
increase_rate_percent_down=8
decrease_rate_percent_down=10

delay_low_target_up=6
delay_high_target_up=15
delay_low_target_down=7
delay_high_target_down=18

latency_filter=median
latency_window_size=5

ping_interval_ms=250
ping_interval_fast_ms=150
elastic_probe=1
elastic_variance_ms=2

adaptive_floor=1
adaptive_floor_step=5
adaptive_floor_max=70
adaptive_floor_trigger_ms=15
adaptive_floor_trigger_count=5

# Decay settings
adaptive_floor_min=55
adaptive_floor_decay_interval=120
adaptive_floor_decay_step=5

load_aware=1
load_check_interval=3
load_bias_decrease=8
load_bias_threshold_bytes=4000000

